# Based on sonarqube ansible role https://github.com/lean-delivery/ansible-role-sonarqube
- name: Wait for sonarqube to be healthy
  uri:
    url: '{{ sonar_check_url }}/api/system/status'
    method: GET
    validate_certs: false
  retries: 120
  delay: 2
  register: result
  until: result.status == 200

- name: Verify login with old password
  uri:
    url: '{{ sonar_check_url }}/api/authentication/login'
    method: POST
    force_basic_auth: true
    user: '{{ sonar_web_user }}'
    password: '{{ sonar_web_old_password }}'
    body: 'login={{ sonar_web_user }}&password={{ sonar_web_old_password }}'
    body_format: form-urlencoded
    validate_certs: false
    status_code:
      - 200
      - 401
  retries: 120
  delay: 2
  register: login_result
  until: login_result.status != 404

- name: Update sonar web password
  uri:
    url: '{{ sonar_check_url }}/api/users/change_password'
    method: POST
    force_basic_auth: true
    user: '{{ sonar_web_user }}'
    password: '{{ sonar_web_old_password }}'
    body: 'login={{ sonar_web_user }}&password={{ sonar_web_password }}&previousPassword={{ sonar_web_old_password }}'
    body_format: form-urlencoded
    validate_certs: false
    status_code: 204
  when:
    - login_result.status == 200
